### ISSUE TITLE
Add highlighting for boost-build

### ISSUE THREAD

**Issue by thomassuckow** [prenaux/atom-language-ham#1]
Might as well add
```
Jamroot
Jamfile.v2
```

**Comment by thomassuckow** [comment]
On second thought. I'll make my own plugin. There are nuances that this plugin doesn't handle and it probably is boost.builds fault.

**Comment by prenaux** [comment]
Note that I'm ok if you want to change it a bit to support boost build, its very simple atm, it really just handles syntax highlighting of the main keywords and basic indentation.
